# Paths to ignore during linting
excluded:
  - Pods
  - Carthage
  - DerivedData
  - BudgetBookPackage/.build
  - fastlane
  - vendor
  - BudgetBookPackage/Sources/Resources
  - BudgetBookPackage/Package.resolved
  - BudgetBookPackage/Package.swift

# Enabled rules
opt_in_rules:
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - conditional_returns_on_newline
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - discouraged_object_literal
  - empty_collection_literal
  - empty_count
  - empty_string
  - empty_xctest_method
  - explicit_init
  - explicit_top_level_acl
  - extension_access_modifier
  - fallthrough
  - fatal_error_message
  - file_name
  - force_unwrapping
  - function_default_parameter_at_end
  - identical_operands
  - implicit_return
  - indentation_width
  - joined_default_parameter
  - last_where
  - legacy_multiple
  - legacy_random
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - modifier_order
  - multiline_arguments
  - multiline_arguments_brackets
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - nimble_operator
  - no_extension_access_modifier
  - number_separator
  - object_literal
  - operator_usage_whitespace
  - optional_enum_case_matching
  - override_in_extension
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - prefer_zero_over_explicit_init
  - redundant_nil_coalescing
  - redundant_type_annotation
  - sorted_first_last
  - sorted_imports
  - strict_fileprivate
  - switch_case_on_newline
  - toggle_bool
  - trailing_closure
  - unused_closure_parameter
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_between_cases
  - yoda_condition

# Rule configurations
analyzer_rules:
  - unused_declaration
  - unused_import

force_cast: warning
force_try: warning
force_unwrapping: warning

identifier_name:
  min_length: 2
  excluded:
    - id
    - to
    - at
    - of
    - up
    - on
    - no
    - vm
    - vc
    - x
    - y
    - i
    - j

line_length:
  warning: 180
  error: 250
  ignores_comments: true
  ignores_urls: true

multiline_arguments:
  first_argument_location: next_line

nesting:
  type_level:
    warning: 4
    error: 6
  function_level:
    warning: 5
    error: 7

trailing_whitespace:
  ignores_empty_lines: true

vertical_whitespace:
  max_empty_lines: 2

# Reporter type (xcode, json, csv, checkstyle, codeclimate, junit, html, emoji, sonarqube, markdown, github-actions-logging)
reporter: "xcode"
